/*//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.14 at 10:42:21 PM GMT+05:30 
//


package com.up;

import javax.xml.bind.annotation.XmlRegistry;


*//**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.up package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 *//*
@XmlRegistry
public class ObjectFactory {


    *//**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.up
     * 
     *//*
    public ObjectFactory() {
    }

    *//**
     * Create an instance of {@link Root }
     * 
     *//*
    public Root createRoot() {
        return new Root();
    }

    *//**
     * Create an instance of {@link Root.Configurations }
     * 
     *//*
    public Root.Configurations createRootConfigurations() {
        return new Root.Configurations();
    }

    *//**
     * Create an instance of {@link Root.Configurations.Instance }
     * 
     *//*
    public Root.Configurations.Instance createRootConfigurationsInstance() {
        return new Root.Configurations.Instance();
    }

    *//**
     * Create an instance of {@link Root.Configurations.Instance.Destination }
     * 
     *//*
    public Root.Configurations.Instance.Destination createRootConfigurationsInstanceDestination() {
        return new Root.Configurations.Instance.Destination();
    }

    *//**
     * Create an instance of {@link Root.Readids }
     * 
     *//*
    public Root.Readids createRootReadids() {
        return new Root.Readids();
    }

    *//**
     * Create an instance of {@link Root.Writeids }
     * 
     *//*
    public Root.Writeids createRootWriteids() {
        return new Root.Writeids();
    }

    *//**
     * Create an instance of {@link Root.Configurations.Instance.Destination.Dutype }
     * 
     *//*
    public Root.Configurations.Instance.Destination.Dutype createRootConfigurationsInstanceDestinationDutype() {
        return new Root.Configurations.Instance.Destination.Dutype();
    }

}
*/