//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.14 at 10:42:21 PM GMT+05:30 
//


package com.up;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="configurations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="instance">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="destination">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="dutype">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="readids">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hasreadaccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="noreadaccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="notvalid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="writeids">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="haswriteaccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nowriteaccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="notvalid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valid",
    "message",
    "configurations",
    "readids",
    "writeids"
})
@XmlRootElement(name = "root")
public class Root {

    protected boolean valid;
    @XmlElement(required = true)
    protected String message;
    @XmlElement(required = true)
    protected Root.Configurations configurations;
    @XmlElement(required = true)
    protected Root.Readids readids;
    @XmlElement(required = true)
    protected Root.Writeids writeids;

    /**
     * Gets the value of the valid property.
     * 
     */
    public boolean isValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     */
    public void setValid(boolean value) {
        this.valid = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the configurations property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Configurations }
     *     
     */
    public Root.Configurations getConfigurations() {
        return configurations;
    }

    /**
     * Sets the value of the configurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Configurations }
     *     
     */
    public void setConfigurations(Root.Configurations value) {
        this.configurations = value;
    }

    /**
     * Gets the value of the readids property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Readids }
     *     
     */
    public Root.Readids getReadids() {
        return readids;
    }

    /**
     * Sets the value of the readids property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Readids }
     *     
     */
    public void setReadids(Root.Readids value) {
        this.readids = value;
    }

    /**
     * Gets the value of the writeids property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Writeids }
     *     
     */
    public Root.Writeids getWriteids() {
        return writeids;
    }

    /**
     * Sets the value of the writeids property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Writeids }
     *     
     */
    public void setWriteids(Root.Writeids value) {
        this.writeids = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="instance">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="destination">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="dutype">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "message",
        "instance"
    })
    public static class Configurations {

        @XmlElement(required = true)
        protected String message;
        @XmlElement(required = true)
        protected Root.Configurations.Instance instance;

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

        /**
         * Gets the value of the instance property.
         * 
         * @return
         *     possible object is
         *     {@link Root.Configurations.Instance }
         *     
         */
        public Root.Configurations.Instance getInstance() {
            return instance;
        }

        /**
         * Sets the value of the instance property.
         * 
         * @param value
         *     allowed object is
         *     {@link Root.Configurations.Instance }
         *     
         */
        public void setInstance(Root.Configurations.Instance value) {
            this.instance = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="destination">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="dutype">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "message",
            "destination"
        })
        public static class Instance {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String message;
            @XmlElement(required = true)
            protected Root.Configurations.Instance.Destination destination;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the message property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMessage() {
                return message;
            }

            /**
             * Sets the value of the message property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMessage(String value) {
                this.message = value;
            }

            /**
             * Gets the value of the destination property.
             * 
             * @return
             *     possible object is
             *     {@link Root.Configurations.Instance.Destination }
             *     
             */
            public Root.Configurations.Instance.Destination getDestination() {
                return destination;
            }

            /**
             * Sets the value of the destination property.
             * 
             * @param value
             *     allowed object is
             *     {@link Root.Configurations.Instance.Destination }
             *     
             */
            public void setDestination(Root.Configurations.Instance.Destination value) {
                this.destination = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="dutype">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "message",
                "dutype"
            })
            public static class Destination {

                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected String message;
                @XmlElement(required = true)
                protected Root.Configurations.Instance.Destination.Dutype dutype;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the message property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMessage() {
                    return message;
                }

                /**
                 * Sets the value of the message property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMessage(String value) {
                    this.message = value;
                }

                /**
                 * Gets the value of the dutype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Root.Configurations.Instance.Destination.Dutype }
                 *     
                 */
                public Root.Configurations.Instance.Destination.Dutype getDutype() {
                    return dutype;
                }

                /**
                 * Sets the value of the dutype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Root.Configurations.Instance.Destination.Dutype }
                 *     
                 */
                public void setDutype(Root.Configurations.Instance.Destination.Dutype value) {
                    this.dutype = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "message"
                })
                public static class Dutype {

                    @XmlElement(required = true)
                    protected String name;
                    @XmlElement(required = true)
                    protected String message;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the message property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getMessage() {
                        return message;
                    }

                    /**
                     * Sets the value of the message property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setMessage(String value) {
                        this.message = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="hasreadaccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="noreadaccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="notvalid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hasreadaccess",
        "noreadaccess",
        "notvalid"
    })
    public static class Readids {

        @XmlElement(required = true)
        protected String hasreadaccess;
        @XmlElement(required = true)
        protected String noreadaccess;
        @XmlElement(required = true)
        protected String notvalid;

        /**
         * Gets the value of the hasreadaccess property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHasreadaccess() {
            return hasreadaccess;
        }

        /**
         * Sets the value of the hasreadaccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHasreadaccess(String value) {
            this.hasreadaccess = value;
        }

        /**
         * Gets the value of the noreadaccess property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNoreadaccess() {
            return noreadaccess;
        }

        /**
         * Sets the value of the noreadaccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNoreadaccess(String value) {
            this.noreadaccess = value;
        }

        /**
         * Gets the value of the notvalid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotvalid() {
            return notvalid;
        }

        /**
         * Sets the value of the notvalid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotvalid(String value) {
            this.notvalid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="haswriteaccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nowriteaccess" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="notvalid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "haswriteaccess",
        "nowriteaccess",
        "notvalid"
    })
    public static class Writeids {

        @XmlElement(required = true)
        protected String haswriteaccess;
        @XmlElement(required = true)
        protected String nowriteaccess;
        @XmlElement(required = true)
        protected String notvalid;

        /**
         * Gets the value of the haswriteaccess property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHaswriteaccess() {
            return haswriteaccess;
        }

        /**
         * Sets the value of the haswriteaccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHaswriteaccess(String value) {
            this.haswriteaccess = value;
        }

        /**
         * Gets the value of the nowriteaccess property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNowriteaccess() {
            return nowriteaccess;
        }

        /**
         * Sets the value of the nowriteaccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNowriteaccess(String value) {
            this.nowriteaccess = value;
        }

        /**
         * Gets the value of the notvalid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotvalid() {
            return notvalid;
        }

        /**
         * Sets the value of the notvalid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotvalid(String value) {
            this.notvalid = value;
        }

    }

}
